function Data() {
  let metropolitaneImg = [
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
    "metropolitane",
  ];

  let urbaneImg = [
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
    "urbane",
  ];

  let tramvaieImg = [
    "firobuze",
    "firobuze",
    "firobuze",
    "firobuze",
    "firobuze",
    "firobuze",
    "tramvaie",
    "tramvaie",
    "tramvaie",
    "tramvaie",
    "tramvaie",
    "tramvaie",
    "tramvaie",
    "tramvaie",
  ];
}

export default Data;
